'use client';
import { useState } from 'react';

export default function LandingPage() {
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [email, setEmail] = useState('');
  const [submitted, setSubmitted] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    try {
      const response = await fetch('https://formspree.io/f/xlgvzabv', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({ email })
      });

      if (response.ok) {
        setSubmitted(true);
      } else {
        console.error("Submission failed.");
      }
    } catch (error) {
      console.error("Error submitting form:", error);
    }
  };

  return (
    <div className="min-h-screen bg-black text-zinc-100 font-sans selection:bg-zinc-800">
      {/* 네비게이션 바 */}
      <nav className="flex justify-between items-center p-6 max-w-5xl mx-auto">
        <div className="font-extrabold text-2xl tracking-tighter cursor-default">
          aeno<span className="text-zinc-600">ex.</span>
        </div>
      </nav>

      {/* 헤드라인 (Hero Section) */}
      <main className="max-w-5xl mx-auto px-6 pt-32 pb-24 text-center">
        <h1 className="text-5xl md:text-7xl font-bold tracking-tighter">
          Stop Chasing Creators for <br/> <span className="text-blue-500">Day-30 Analytics.</span>
        </h1>
        <p className="text-lg text-zinc-400 mt-6 max-w-2xl mx-auto">
          Drop a YouTube or Spotify URL. We automatically capture the 30-day snapshot and generate a white-labeled PDF report for your sponsors. No more manual screenshots and Excel nightmares.
        </p>
        <button
          onClick={() => setIsModalOpen(true)}
          className="bg-zinc-100 text-black px-8 py-4 rounded-full font-bold text-lg hover:bg-white hover:scale-105 transition-all duration-200 shadow-[0_0_40px_rgba(255,255,255,0.1)]"
        >
          See Sample Report
        </button>

        {/* Mock PDF Report 시각화 */}
        <div className="mt-16 flex justify-center">
          <div className="w-full max-w-2xl bg-white text-black rounded-2xl overflow-hidden shadow-2xl shadow-blue-900/20 -rotate-1 hover:rotate-0 transition-transform duration-500">
            {/* PDF 헤더 */}
            <div className="bg-zinc-50 border-b border-zinc-200 px-6 py-4 flex items-center justify-between">
              <div className="flex items-center gap-3">
                <div className="w-8 h-8 bg-blue-100 rounded-lg flex items-center justify-center text-blue-600 font-bold text-xs">
                  A
                </div>
                <div>
                  <p className="text-xs text-zinc-400 font-medium">Agency Logo Placeholder</p>
                  <p className="text-sm font-bold text-zinc-800">Day-30 Campaign Snapshot</p>
                </div>
              </div>
              <div className="text-right">
                <p className="text-[10px] text-zinc-400">Report ID: #SNP-2026-10-12</p>
                <p className="text-[10px] text-zinc-400">Generated by aenoex</p>
              </div>
            </div>

            {/* PDF 본문 */}
            <div className="p-6 space-y-5">
              {/* 크리에이터 정보 */}
              <div className="flex items-center gap-3 pb-4 border-b border-zinc-100">
                <div className="w-10 h-10 bg-zinc-200 rounded-full flex items-center justify-center text-zinc-500 font-bold text-sm">
                  YT
                </div>
                <div>
                  <p className="text-sm font-bold text-zinc-800">Tech Review - NordVPN Integration</p>
                  <p className="text-xs text-zinc-400">youtube.com/watch?v=example</p>
                </div>
              </div>

              {/* 타임스탬프 */}
              <div className="flex items-center gap-2 text-xs text-zinc-500 bg-zinc-50 px-3 py-2 rounded-lg border border-zinc-100">
                <span className="text-zinc-400">📅</span>
                <span>Timestamp: Oct 12, 2026, 14:00 UTC (Exactly Day 30)</span>
              </div>

              {/* 핵심 지표 */}
              <div className="bg-gradient-to-r from-blue-50 to-indigo-50 rounded-xl p-5 border border-blue-100">
                <p className="text-xs text-blue-600 font-semibold uppercase tracking-wider mb-1">Total Views</p>
                <p className="text-4xl md:text-5xl font-extrabold text-zinc-900 tracking-tight">452,109</p>
                <div className="flex items-center gap-2 mt-2">
                  <span className="text-xs text-green-600 bg-green-100 px-2 py-0.5 rounded-full font-medium">▲ +12.3% vs Day 7</span>
                  <span className="text-xs text-zinc-400">| Locked at Day 30</span>
                </div>
              </div>

              {/* 증빙: 썸네일 + 그래프 */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {/* 유튜브 썸네일 영역 */}
                <div className="bg-zinc-100 rounded-xl overflow-hidden border border-zinc-200">
                  <div className="aspect-video bg-gradient-to-br from-zinc-300 to-zinc-400 flex items-center justify-center relative">
                    <div className="w-12 h-12 bg-black/70 rounded-full flex items-center justify-center">
                      <span className="text-white text-lg ml-0.5">▶</span>
                    </div>
                    <div className="absolute bottom-2 right-2 bg-black/80 text-white text-[10px] px-1.5 py-0.5 rounded font-mono">
                      14:32
                    </div>
                  </div>
                  <div className="px-3 py-2 flex items-center justify-between">
                    <div className="flex items-center gap-1.5">
                      <div className="w-5 h-5 bg-zinc-300 rounded-full"></div>
                      <span className="text-[11px] text-zinc-500 font-medium">Tech Review</span>
                    </div>
                    <span className="text-[11px] text-zinc-400">452K views</span>
                  </div>
                </div>

                {/* 조회수 추이 그래프 */}
                <div className="bg-zinc-50 rounded-xl p-4 border border-zinc-200">
                  <p className="text-[11px] text-zinc-500 font-semibold mb-3">Views Growth (30 Days)</p>
                  <div className="flex items-end gap-1.5 h-24">
                    <div className="flex-1 bg-blue-200 rounded-t" style={{ height: '20%' }}></div>
                    <div className="flex-1 bg-blue-300 rounded-t" style={{ height: '35%' }}></div>
                    <div className="flex-1 bg-blue-400 rounded-t" style={{ height: '50%' }}></div>
                    <div className="flex-1 bg-blue-500 rounded-t" style={{ height: '65%' }}></div>
                    <div className="flex-1 bg-blue-600 rounded-t" style={{ height: '80%' }}></div>
                    <div className="flex-1 bg-blue-500 rounded-t" style={{ height: '75%' }}></div>
                    <div className="flex-1 bg-blue-400 rounded-t" style={{ height: '60%' }}></div>
                    <div className="flex-1 bg-blue-300 rounded-t" style={{ height: '45%' }}></div>
                    <div className="flex-1 bg-blue-200 rounded-t" style={{ height: '30%' }}></div>
                    <div className="flex-1 bg-blue-100 rounded-t" style={{ height: '15%' }}></div>
                  </div>
                  <div className="flex justify-between mt-2 text-[9px] text-zinc-400">
                    <span>Day 1</span>
                    <span>Day 7</span>
                    <span>Day 14</span>
                    <span>Day 21</span>
                    <span>Day 30</span>
                  </div>
                </div>
              </div>

              {/* 푸터 */}
              <div className="pt-3 border-t border-zinc-100 flex items-center justify-between text-[10px] text-zinc-400">
                <span>🔒 This report is timestamped and verified.</span>
                <span className="font-mono">aenoex · SponsorSnap</span>
              </div>
            </div>
          </div>
        </div>
      </main>

      {/* 핵심 가치 증명 (Features) */}
      <section className="max-w-5xl mx-auto px-6 py-24 grid grid-cols-1 md:grid-cols-3 gap-12 border-t border-zinc-900">
        <div>
          <h3 className="text-xl font-bold mb-4 text-white">Fire and Forget</h3>
          <p className="text-zinc-500 leading-relaxed">
            Paste the URL once. We track the exact release date and automatically ping the API 30 days later.
          </p>
        </div>
        <div>
          <h3 className="text-xl font-bold mb-4 text-white">White-labeled PDFs</h3>
          <p className="text-zinc-500 leading-relaxed">
            Your agency's logo, your branding. We generate professional snapshot reports ready to forward to sponsors.
          </p>
        </div>
        <div>
          <h3 className="text-xl font-bold mb-4 text-white">Bulletproof Proof</h3>
          <p className="text-zinc-500 leading-relaxed">
            Stop arguing over changing numbers. We timestamp and lock the views/listens at the exact agreed-upon hour.
          </p>
        </div>
      </section>

      {/* 작동 예시 (Mock Dashboard List) */}
      <section className="max-w-4xl mx-auto px-6 py-12 mb-12">
        <div className="bg-[#09090b] border border-zinc-800 rounded-xl overflow-hidden shadow-2xl">
          <div className="flex flex-col md:flex-row items-center justify-between px-6 py-4 border-b border-zinc-800 bg-black/50">
            <span className="text-sm font-semibold text-zinc-200">Active Campaigns</span>
            <div className="flex gap-2 mt-4 md:mt-0">
              <input type="text" placeholder="Paste YouTube/Spotify URL..." className="bg-zinc-900 border border-zinc-700 text-sm rounded-md px-3 py-1.5 w-64 text-zinc-300 focus:outline-none" disabled />
              <button className="bg-blue-600 text-white text-sm px-4 py-1.5 rounded-md font-medium">Track</button>
            </div>
          </div>
          <div className="p-6">
            <div className="flex items-center justify-between py-3 border-b border-zinc-800/50">
              <div className="flex items-center gap-3">
                <div className="w-2 h-2 rounded-full bg-green-500 animate-pulse"></div>
                <span className="text-sm text-zinc-300">Tech Review - NordVPN Integration</span>
              </div>
              <div className="flex items-center gap-6">
                <span className="text-xs text-zinc-500">Day 28 / 30</span>
                <span className="text-xs font-mono bg-blue-500/10 text-blue-400 px-2 py-1 rounded">Capturing in 48h</span>
              </div>
            </div>
            <div className="flex items-center justify-between py-3">
              <div className="flex items-center gap-3">
                <div className="w-2 h-2 rounded-full bg-zinc-600"></div>
                <span className="text-sm text-zinc-500">Podcast Ep.14 - BetterHelp</span>
              </div>
              <div className="flex items-center gap-6">
                <span className="text-xs text-zinc-500">Day 30 / 30</span>
                <span className="text-xs font-mono bg-green-500/10 text-green-400 px-2 py-1 rounded">PDF Sent to Sponsor</span>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* 대기자 명단 팝업 모달 (Waitlist Trap) */}
      {isModalOpen && (
        <div className="fixed inset-0 bg-black/90 backdrop-blur-sm flex items-center justify-center p-4 z-50">
          <div className="bg-[#09090b] border border-zinc-800 p-8 rounded-2xl max-w-md w-full relative shadow-2xl">
            <button 
              onClick={() => setIsModalOpen(false)} 
              className="absolute top-5 right-5 text-zinc-500 hover:text-white text-xl"
            >
              &times;
            </button>
            {!submitted ? (
              <>
                <h2 className="text-2xl font-bold mb-3 text-white">Get Your Sample Report</h2>
                <p className="text-zinc-400 mb-6 text-sm leading-relaxed">
                  Join the waitlist to see how our white-labeled PDF looks, and get early access to the beta.
                </p>
                <form onSubmit={handleSubmit} className="flex flex-col gap-4">
                  <input
                    type="email"
                    required
                    placeholder="enter your work email..."
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                    className="bg-black border border-zinc-800 rounded-xl px-4 py-3 text-white placeholder:text-zinc-600 focus:outline-none focus:border-zinc-500 focus:ring-1 focus:ring-zinc-500 transition-all"
                  />
                  <button 
                    type="submit" 
                    className="bg-white text-black font-bold rounded-xl px-4 py-3 hover:bg-zinc-200 transition-colors"
                  >
                    Join the Waitlist
                  </button>
                </form>
              </>
            ) : (
              <div className="text-center py-8">
                <div className="w-16 h-16 bg-zinc-900 rounded-full flex items-center justify-center mx-auto mb-4 border border-zinc-800">
                  <span className="text-2xl">🤝</span>
                </div>
                <h2 className="text-xl font-bold mb-2 text-white">Added to waitlist!</h2>
                <p className="text-zinc-500 text-sm">Keep an eye on your inbox. We'll be in touch soon.</p>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
